# Generated by Django 3.1.4 on 2021-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210309_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='draft', max_length=255),
        ),
    ]
