# Generated by Django 3.1.4 on 2021-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
