# Generated by Django 3.1.4 on 2021-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmedia_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='range_type',
            field=models.CharField(blank=True, choices=[('from', 'From'), ('to', 'To')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('image', 'Image'), ('dropdown', 'Dropdown'), ('range', 'Range')], max_length=255),
        ),
    ]
