# Generated by Django 3.1.4 on 2021-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210128_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='attribute',
            name='view_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=255, null=True),
        ),
    ]
