# Generated by Django 3.1.4 on 2021-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210128_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='range_type',
            field=models.CharField(blank=True, choices=[('from', 'کمترین'), ('to', 'بیشترین')], max_length=255, null=True),
        ),
    ]
