# Generated by Django 3.1.4 on 2021-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210128_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='view_type',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('image', 'Image'), ('dropdown', 'Dropdown'), ('range', 'Range'), ('multiple', 'Multiple Choice')], max_length=255),
        ),
    ]
