# Generated by Django 3.1.4 on 2021-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210314_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'کیلوگرم'), ('ton', 'تن'), ('mm', 'میلی\u200cمتر'), ('cm', 'سانتی\u200cمتر')], max_length=255),
        ),
    ]
