# Generated by Django 3.1.4 on 2021-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210128_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=255),
        ),
    ]
