# Generated by Django 3.1.4 on 2021-04-20 09:17

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210314_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemedia',
            name='file',
            field=models.FileField(upload_to=apps.products.models.get_product_file_path),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to=apps.products.models.get_product_file_path),
        ),
    ]
