# Generated by Django 3.1.4 on 2021-03-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210227_2054'),
        ('products', '0010_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mine'),
        ),
    ]
