# Generated by Django 3.1.4 on 2021-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_mine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=255),
        ),
    ]
