# Generated by Django 3.1.4 on 2021-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210420_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='child_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
    ]
