# Generated by Django 3.1.4 on 2021-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210315_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticorder',
            name='state',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], max_length=255),
        ),
    ]
