# Generated by Django 3.1.4 on 2021-03-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210315_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='orders')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogisticOrderMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='orders')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='orders.logisticorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
