# Generated by Django 3.1.4 on 2021-03-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210315_1823'),
        ('orders', '0009_auto_20210315_1659'),
    ]

    operations = [
    ]
