# Generated by Django 3.1.4 on 2021-03-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20210317_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistic_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='orders.logisticorder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='monthly_load',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
