# Generated by Django 3.1.4 on 2021-04-20 09:17

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210324_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticordermedia',
            name='file',
            field=models.FileField(upload_to=apps.orders.models.get_order_file_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('submitted', 'ثبت سفارش'), ('pending_admin', 'تایید سایت'), ('pending_seller', 'تایید فروشنده'), ('pending_logistic', 'تایید حمل و نقل'), ('pending_buyer_logistic_price', 'تایید قیمت حمل و نقل توسط خریدار'), ('pending_contract', 'تایید قرارداد'), ('pending_finance_documents', 'تایید مدارک مالی'), ('accepted', 'تایید نهایی'), ('finished', 'انجام شده')], default='submitted', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermedia',
            name='file',
            field=models.FileField(upload_to=apps.orders.models.get_order_file_path),
        ),
    ]
