# Generated by Django 3.1.4 on 2021-04-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210420_0917'),
        ('orders', '0013_auto_20210420_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticorder',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
        migrations.AddField(
            model_name='logisticorder',
            name='monthly_load_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logisticorder',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mine'),
        ),
        migrations.AddField(
            model_name='logisticorder',
            name='weight',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logisticorder',
            name='state',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('contract', 'تایید مدارک'), ('finance', 'تایید مدارک مالی'), ('rejected', 'رد شده')], max_length=255),
        ),
    ]
