kind: pipeline
type: docker
name: "Madan Deployment"

clone:
  depth: 1

steps:
  - name: build
    image: docker
    pull: never
    commands:
      - docker build -t madan:1.0.0 .
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      branch: master
      event:
        - push
        - pull_request

  - name: deploy
    image: docker/compose
    pull: never
    commands:
      - docker-compose up -d
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      branch: master
      event:
        - push
        - pull_request

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
