kind: pipeline
type: docker
name: "Madan"

clone:
  depth: 1

steps:
  - name: build
    image: docker
    pull: never
    commands:
      - docker build -t madan:1.0.0 .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event:
        - push
        - pull_request

  - name: deploy
    image: docker/compose
    pull: never
    commands: :
      - docker-compose up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event:
        - push
        - pull_request

