version: '2'
services:
  web:
    image: madan:1.0.0
    container_name: "madan_web"
    restart: always
    depends_on:
      - db
    volumes:
    - /opt/madan/logs:/project/logs
    - /opt/madan/db.sqlite3:/project/db.sqlite3
    ports:
    - 0.0.0.0:7000:8000

  db:
    image: postgres:alpine
    container_name: "madan_db"
    restart: always
    volumes:
    - /opt/madan/data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_PASSWORD=Planhub@123
