version: '2'
services:
  web:
    image: madan:1.0.0
    container_name: "madan_web"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
    - /opt/madan/logs:/project/logs
    - /opt/madan/media:/project/media
    - /opt/madan/static:/project/static
    - /opt/madan/config/:/project/config
    ports:
    - 0.0.0.0:7000:8000
    environment:
      - "DJANGO_DEBUG=true"
      - "DJANGO_STAGING=true"
      - "DJANGO_DATABASE_PASSWORD=Planhub@123"

  db:
    image: postgres:alpine
    container_name: "madan_db"
    restart: always
    volumes:
    - /opt/madan/data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_USER=planhub
      - POSTGRES_PASSWORD=Planhub@123
      - POSTGRES_DB=madan

  redis:
    image: redis:alpine
    container_name: "madan_redis"
    restart: always
    environment:
      - TZ=Asia/Tehran

  nginx:
    image: nginx:alpine
    container_name: "madan_nginx"
    volumes:
      - /opt/madan/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/madan/static:/opt/static
      - /opt/madan/media:/opt/media
    ports:
      - 127.0.0.1:8000:80
    links:
      - web:web
    depends_on:
      - stoneet
    restart: always