version: '2'
services:
  web:
    build: .
    container_name: "madan_web"
    restart: always
    depends_on:
      - db
    volumes:
    - .:/project
    ports:
    - 127.0.0.1:8000:8000

  db:
    image: postgres:alpine
    container_name: "madan_db"
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      TZ: "Asia/Tehran"
