version: '2'
services:
  web:
    image: madan:1.0.0
    container_name: "madan_web"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
    - ./logs:/project/logs
    - ./media:/project/media
    - ./assets:/project/assets
    - ./config:/project/config
    ports:
    - 0.0.0.0:7000:8000
    environment:
      - "DJANGO_DATABASE_PASSWORD=Planhub@123"
      - "DJANGO_ENV=prod"

  db:
    image: postgres:alpine
    container_name: "madan_db"
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_USER=planhub
      - POSTGRES_PASSWORD=Planhub@123
      - POSTGRES_DB=madan

  redis:
    image: redis:alpine
    container_name: "madan_redis"
    restart: always
    environment:
      - TZ=Asia/Tehran

  nginx:
    image: nginx:alpine
    container_name: "madan_nginx"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./assets:/opt/assets:ro
      - ./media:/opt/media:ro
    ports:
      - 127.0.0.1:8000:80
    links:
      - web:web
    depends_on:
      - web
    restart: always
