# Generated by Django 3.1.4 on 2021-06-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210430_2247'),
        ('invoices', '0002_auto_20210306_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
