# Generated by Django 3.1.4 on 2021-06-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210620_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='publish_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
