# Generated by Django 3.1.4 on 2021-06-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210620_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('پیش فاکتور', 'پیش فاکتور'), ('پرداخت شده', 'پرداخت شده'), ('پرداخت نشده', 'پرداخت نشده')], default='pre', max_length=255),
            preserve_default=False,
        ),
    ]
