# Generated by Django 3.1.4 on 2021-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20210422_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[('started', 'شروع شده'), ('in_progress', 'در حال انجام'), ('finished', 'تمام شده'), ('expired', 'منقضی شده')], max_length=255),
        ),
    ]
