# Generated by Django 3.1.4 on 2021-08-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangerequest',
            name='state',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('resolved', 'انجام شده'), ('rejected', 'رد شده')], default='pending', max_length=255),
            preserve_default=False,
        ),
    ]
