# Generated by Django 3.1.4 on 2021-03-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('terms_logistic', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
            ],
        ),
    ]
