# Generated by Django 3.1.4 on 2021-03-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticcontent',
            old_name='terms_conditions',
            new_name='terms_seller',
        ),
    ]
