# Generated by Django 3.1.4 on 2021-01-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Locations'},
        ),
    ]
