# Generated by Django 3.1.4 on 2021-03-06 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('mobile_number', models.CharField(db_index=True, default='021xxxxxxxx', max_length=20)),
                ('use_type', models.CharField(choices=[('seller', 'Seller'), ('logistic', 'Logistic'), ('buyer', 'Buyer'), ('admin', 'Admin'), ('superuser', 'Super User')], default='buyer', max_length=20)),
                ('legal_type', models.CharField(choices=[('individual', 'حقیقی'), ('legal', 'حقوقی')], default='individual', max_length=20)),
                ('state', models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('banned', 'مسدود شده')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=255)),
                ('file', models.FileField(upload_to='users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=255)),
                ('id_code', models.CharField(blank=True, max_length=255)),
                ('national_code', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('bank_account_name', models.CharField(blank=True, max_length=255)),
                ('bank_sheba_number', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_type', models.CharField(blank=True, choices=[('am', 'عام'), ('khas', 'خاص'), ('masouliat_mahdood', 'مسئولیت محدود'), ('taavoni', 'تعاونی')], max_length=255, null=True)),
                ('company_register_code', models.CharField(blank=True, max_length=255)),
                ('company_national_code', models.CharField(blank=True, max_length=255)),
                ('company_finance_code', models.CharField(blank=True, max_length=255)),
                ('company_print_signature_right', models.CharField(blank=True, max_length=255)),
                ('company_license_type', models.CharField(blank=True, max_length=255)),
                ('company_license_code', models.CharField(blank=True, max_length=255)),
                ('company_license_start', models.DateField(blank=True, null=True)),
                ('company_license_end', models.DateField(blank=True, null=True)),
                ('company_ceo_name', models.CharField(blank=True, max_length=255)),
                ('company_ceo_id_code', models.CharField(blank=True, max_length=255)),
                ('company_ceo_national_code', models.CharField(blank=True, max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('road_name', models.CharField(blank=True, max_length=255)),
                ('location_in_region', models.CharField(choices=[('north', 'شمال'), ('south', 'جنوب'), ('east', 'شرق'), ('west', 'غرب')], max_length=255)),
                ('distance_to_road', models.IntegerField()),
                ('proper_road', models.BooleanField()),
                ('load_tools', models.BooleanField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('road_name', models.CharField(max_length=255)),
                ('distance_to_road', models.IntegerField()),
                ('proper_road', models.BooleanField()),
                ('load_tools', models.BooleanField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
