# Generated by Django 3.1.4 on 2021-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('logistic', 'Logistic'), ('buyer', 'Buyer'), ('admin', 'Admin'), ('superuser', 'Super User')], default='buyer', max_length=20),
        ),
    ]
