# Generated by Django 3.1.4 on 2021-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('pending', 'Waiting For Confirm'), ('accepted', 'Confirmed'), ('rejected', 'Rejected'), ('banned', 'Banned')], default='pending', max_length=20),
        ),
    ]
