# Generated by Django 3.1.4 on 2021-04-20 09:17

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='file',
            field=models.FileField(upload_to=apps.users.models.get_user_file_path),
        ),
    ]
