# Generated by Django 3.1.4 on 2021-02-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210125_1320'),
        ('users', '0004_auto_20210125_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fax_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.CreateModel(
            name='SellerLegalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('sheba_number', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('company_register_code', models.CharField(max_length=255)),
                ('company_national_code', models.CharField(max_length=255)),
                ('company_finance_code', models.CharField(max_length=255)),
                ('company_print_signature_right', models.CharField(max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerIndividualProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('sheba_number', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('id_code', models.CharField(blank=True, max_length=255)),
                ('national_code', models.CharField(blank=True, max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogisticProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('sheba_number', models.CharField(blank=True, max_length=255)),
                ('company_license_type', models.CharField(blank=True, max_length=255)),
                ('company_license_code', models.CharField(blank=True, max_length=255)),
                ('company_license_start', models.DateField(blank=True, null=True)),
                ('company_license_end', models.DateField(blank=True, null=True)),
                ('company_register_code', models.CharField(blank=True, max_length=255)),
                ('company_ceo_name', models.CharField(blank=True, max_length=255)),
                ('company_ceo_id_code', models.CharField(blank=True, max_length=255)),
                ('company_ceo_national_code', models.CharField(max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerLegalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('sheba_number', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('company_register_code', models.CharField(max_length=255)),
                ('company_national_code', models.CharField(max_length=255)),
                ('company_finance_code', models.CharField(max_length=255)),
                ('company_print_signature_right', models.CharField(max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerIndividualProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('sheba_number', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('id_code', models.CharField(blank=True, max_length=255)),
                ('national_code', models.CharField(blank=True, max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profile_buyer_individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.buyerindividualprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_buyer_legal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.buyerlegalprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_logistic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.logisticprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_seller_individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sellerindividualprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_seller_legal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sellerlegalprofile'),
        ),
    ]
