# Generated by Django 3.1.4 on 2021-06-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210420_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_branch_type',
            field=models.CharField(blank=True, choices=[('central', 'شعبه اصلی'), ('branch', 'نماینده شرکت')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_license_type',
            field=models.CharField(blank=True, choices=[('city', 'حمل و نقل شهری'), ('province', 'حمل و نقل استانی'), ('country', 'حمل و نقل سراسری'), ('international', 'حمل و نقل بین\u200cالمللی')], max_length=255),
        ),
    ]
