# Generated by Django 3.1.4 on 2021-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210211_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='distance_to_road',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mine',
            name='load_tools',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mine',
            name='proper_road',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mine',
            name='road_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='state',
            field=models.CharField(choices=[('pending', 'Waiting For Confirm'), ('accepted', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermedia',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
