# Generated by Django 3.1.4 on 2021-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210217_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerindividualprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyerlegalprofile',
            name='company_finance_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyerlegalprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyerlegalprofile',
            name='company_national_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyerlegalprofile',
            name='company_print_signature_right',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyerlegalprofile',
            name='company_register_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyerlegalprofile',
            name='company_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerindividualprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlegalprofile',
            name='company_finance_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerlegalprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerlegalprofile',
            name='company_national_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerlegalprofile',
            name='company_print_signature_right',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerlegalprofile',
            name='company_register_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerlegalprofile',
            name='company_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
