# Generated by Django 3.1.4 on 2021-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expiration',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
