# Generated by Django 3.1.4 on 2021-02-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210125_1320'),
        ('users', '0007_auto_20210218_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('sheba_number', models.CharField(blank=True, max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profile_default',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.defaultprofile'),
        ),
    ]
