# Generated by Django 3.1.4 on 2021-02-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210218_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_buyer_individual',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_buyer_legal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_default',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_logistic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_seller_individual',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_seller_legal',
        ),
        migrations.AddField(
            model_name='buyerindividualprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerlegalprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logisticprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerindividualprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerlegalprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
