# Generated by Django 3.1.4 on 2021-02-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210218_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerindividualprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='buyerlegalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='defaultprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logisticprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerindividualprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerlegalprofile',
            name='user',
        ),
    ]
