# Generated by Django 3.1.4 on 2021-02-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210218_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_buyer_individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.buyerindividualprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_buyer_legal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.buyerlegalprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_default',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.defaultprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_logistic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.logisticprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_seller_individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sellerindividualprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_seller_legal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sellerlegalprofile'),
        ),
    ]
