# Generated by Django 3.1.4 on 2021-02-18 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210125_1320'),
        ('users', '0011_auto_20210218_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('id_code', models.CharField(blank=True, max_length=255)),
                ('national_code', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('sheba_number', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_type', models.CharField(blank=True, max_length=255)),
                ('company_register_code', models.CharField(blank=True, max_length=255)),
                ('company_national_code', models.CharField(blank=True, max_length=255)),
                ('company_finance_code', models.CharField(blank=True, max_length=255)),
                ('company_print_signature_right', models.CharField(blank=True, max_length=255)),
                ('company_license_type', models.CharField(blank=True, max_length=255)),
                ('company_license_code', models.CharField(blank=True, max_length=255)),
                ('company_license_start', models.DateField(blank=True, null=True)),
                ('company_license_end', models.DateField(blank=True, null=True)),
                ('company_ceo_name', models.CharField(blank=True, max_length=255)),
                ('company_ceo_id_code', models.CharField(blank=True, max_length=255)),
                ('company_ceo_national_code', models.CharField(max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyerlegalprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='defaultprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='logisticprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sellerindividualprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sellerlegalprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_buyer_individual',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_buyer_legal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_default',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_logistic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_seller_individual',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_seller_legal',
        ),
        migrations.DeleteModel(
            name='BuyerIndividualProfile',
        ),
        migrations.DeleteModel(
            name='BuyerLegalProfile',
        ),
        migrations.DeleteModel(
            name='DefaultProfile',
        ),
        migrations.DeleteModel(
            name='LogisticProfile',
        ),
        migrations.DeleteModel(
            name='SellerIndividualProfile',
        ),
        migrations.DeleteModel(
            name='SellerLegalProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
