# Generated by Django 3.1.4 on 2021-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210218_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_name',
            new_name='bank_account_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sheba_number',
            new_name='bank_sheba_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_ceo_national_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
