# Generated by Django 3.1.4 on 2021-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210227_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_type',
            field=models.CharField(blank=True, choices=[('am', 'عام'), ('khas', 'خاص'), ('masouliat_mahdood', 'مسئولیت محدود'), ('taavoni', 'تعاونی')], max_length=255),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='state',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=255),
        ),
    ]
